riscv32: Use double-float ABI for rv32
So it can use libgcc built with OE toolchain
Fixes
error: "can't link hard-float modules with soft-float modules"

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Upstream-Status: Inappropriate [embedded specific]

%% original patch: 0001-riscv32-Use-double-float-ABI-for-rv32.patch